#!/usr/bin/env bash
# Display information about subdomains

print () {

}

dig_func () {
	if [ $# -eq 1 ]; then
		dig www."$1" | awk '/ANSWER SECTION:/{getline; print}'
		dig lb-01."$1" | awk '/ANSWER SECTION:/{getline; print}'
		dig web-01."$1" | awk '/ANSWER SECTION:/{getline; print}'
		dig web-02."$1" | awk '/ANSWER SECTION:/{getline; print}'
	elif [ $# -gt 1 ]; then
		dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; print}'
	fi
# echo output in appropriate format
}

if [ $# -eq 1 ]; then
	dig_func "$1"
else
	dig_func "$1" "$2"
fi


# info=$(dig $1 | awk '/ANSWER SECTION:/{getline; print}')
# echo The subdomain $(echo $info | cut -d '.' -f 1) is a $(echo $info | ) record and points to $()

