#!/usr/bin/env bash
# Display information about subdomains

print () {
	echo The subdomain "$1" is a "$2" record and points to "$3"
}

dig_func () {
	if [ $# -eq 1 ]; then
		destination=$(dig www."$1" | awk '/ANSWER SECTION:/{getline; print$5}')
		print www A "$destination"
		destination=$(dig lb-01."$1" | awk '/ANSWER SECTION:/{getline; print$5}')
		print lb-01 A "$destination"
		destination=$(dig web-01."$1" | awk '/ANSWER SECTION:/{getline; print$5}')
		print web-01 A "$destination"
		destination=$(dig web-02."$1" | awk '/ANSWER SECTION:/{getline; print$5}')
		print web-02 A "$destination"
	elif [ $# -gt 1 ]; then
		subdomain=$(dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; print$1}' | cut -d '.' -f 1)
		record_type=$(dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; print$4}')
		destination=$(dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; print$5}')
		print "$subdomain" "$record_type" "$destination"
	fi
}

if [ $# -eq 1 ]; then
	dig_func "$1"
else
	dig_func "$1" "$2"
fi
