#!/usr/bin/env bash
# Configures a new Ubuntu machine with given requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service start nginx
sudo echo 'Holberton School' > /usr/share/nginx/html/index.html
