#!/usr/bin/env bash
# Configures a new Ubuntu machine with given requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
