#!/usr/bin/env bash
# Configures a new Ubuntu machine with given requirements

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo service haproxy start
echo -e '\nfrontend Local_Server\n\tbind *:80\n\tmode http\n\tdefault_backend My_Web_Servers' >> /etc/haproxy/haproxy.cfg
echo -e '\nbackend My_Web_Servers\n\tmode http\n\tbalance roundrobin\n\tserver 668-web-01 35.229.123.177\n\tserver 668-web-02 34.73.72.195' >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

