#!/usr/bin/env bash
# script that creates a file and displays text or takes action in response to different signals
echo $$ >> /var/run/holbertonscript.pid

trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
trap "sudo rm /var/run/holbertonscript.pid; exit" quit_term SIGQUIT

while :
    do
        echo "To infinity and beyond"
        sleep 4
    done
