#!/usr/bin/env bash
# print numbers 1 - 20 and comments
i="0"
while [ $i -lt 20 ]
    do
        i=$((i + 1))
        echo $i
        if [ $i -eq 4 ]
        then
            echo "bad luck from China"
        elif [ $i -eq 9 ]
        then
            echo "bad luck from Japan"
        elif [ $i -eq 17 ]
        then
            echo "bad luck Italy"
        fi
    done
