#!/usr/bin/env bash
# print time for 12 hours and 59 min
hour="0"
min="0"
while [ $hour -lt 13 ]
    do
        echo "Hour: $hour" 
        while [ $min -lt 59 ]
            do
                min=$((min + 1))
                echo $min
            done
        hour=$((hour + 1))
        min=0
    done
