#!/usr/bin/env bash
# Configures Ubuntu server with specifications
cp /etc/hosts ~/hosts.new
sed -i '1i127.0.0.2 localhost' ~/hosts.new
sed -i '1i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
